name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
categories:
  - title: ' :boom: Breaking'
    label: 'type: breaking'
  - title: ':rocket: New'
    label: 'type: feature'
  - title: ':bug: Bug Fixes'
    label: 'type: bug'
  - title: ':wrench: Maintenance'
    label: 'type: maintenance'
  - title: ':book: Documentation'
    label: 'type: docs'
  - title: ':gear: Dependency Updates'
    label: 'type: dependencies'

version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: feature'
  patch:
    labels:
      - 'type: bug'
      - 'type: maintenance'
      - 'type: docs'
      - 'type: dependencies'
      - 'type: security'

exclude-labels:
  - 'skip-changelog'